### ISSUE TITLE
$ undefined error started a few days ago

### ISSUE THREAD

**Issue by jakeonrails** [DrewML/octo-preview#3] opened 2016-05-18 18:56 UTC
Hi there,

I love this extension. Installed it a couple weeks ago and it worked great, until it stopped.

Today I finally got around to investigating and found this:

<img width="391" alt="screen shot 2016-05-18 at 11 55 03 am" src="https://cloud.githubusercontent.com/assets/580084/15371259/781ea49e-1cef-11e6-8983-dba8de35bdc9.png">

Seems like it's trying to use the jQuery $ but maybe Github broke that or the extension isn't including it correctly? I don't understand how that second option could be the case since this project hasn't updated in the Chrome extension store since February.

**Comment by DrewML** [comment] 2016-05-19 02:03
Hey @jakeonrails!

Thanks for pointing this out. [The same issue](https://github.com/DrewML/GifHub/issues/13) happened with another one of my extensions recently. You're pretty much right about the cause - GitHub dropped exposing a global for `$`.

I'll try to get a fix in soon, or you can also submit a PR that does roughly the same thing as [as this commit](https://github.com/DrewML/GifHub/commit/a69298df521f7e342f766a3401427c54b848d0a6) and I'll merge it in + publish :)

**Comment by jakeonrails** [comment] 2016-05-19 20:27
Well, this is weird. I forked and built the project, imported into chrome, and it just worked. So I re-enabled your version, and it still works.

So... maybe we can close this issue now?

**Comment by DrewML** [comment] 2016-05-19 20:45
Do you have another extension installed (maybe even `GifHub`) that might be restoring the global `$`? I just checked in an incognito window and I'm still seeing the issue.

**Comment by jakeonrails** [comment] 2016-05-19 21:09
Oh! I do have GifHub installed. I'll see if I can duplicate the bug again now, and then I'll submit a PR.

**Comment by egoist** [comment] 2016-05-23 08:16
BTW, should `"matches"` be `["*://*/*"]` in `manifest.json`? Better be `["*://github.com/*"]` right?

Otherwise it results in `$ is not a function` in other websites.

**Comment by DrewML** [comment] 2016-05-23 20:20
@egoist It's set to `["*://*/*"]` to be able to support GitHub Enterprise users. I need to change this and just provide an option for a user to enter their GH Enterprise hostname, but haven't gotten around to it yet.

~~Can you give me an example site where you get that error message, though? The changes added by @jakeonrails _shouldn't_ be executing on non-GitHub websites (handled in [this](https://github.com/DrewML/octo-preview/blob/master/shells/chrome/inject.js#L17) code);~~

Nevermind - I see what's happening. Thanks for the heads-up, @egoist. I made a _horrible_ assumption here that other sites `require` fn's would also throw when requiring a non-existent module. Will push a patch tonight.

**Comment by DrewML** [comment] 2016-05-23 20:27
Opened #5 to address the issue.

**Closed as completed by DrewML** 2016-05-23 20:27 UTC
